baseurl         = "/"
theme           = "casper-two"
languageCode    = "jp-JP"
disqusShortname = "RinGoku"
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Hugo Casper Two"
  subtitle    = ""
  copyright   = "© 2019"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "RinGoku98"
  githubName = "RinGoku"
  mediumName = ""

  logo = "hugo-logo.png"
  orgName = "りんごく"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "りんごく"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "東京品川区"
  authorWebsite = "https://ringoku.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95


